"""`paratext new` — scaffold a new project package.

Generates a project directory in the current working directory:

    <name>/
        prompt.md     # the prompt (prose, for the model)
        schema.py     # the Pydantic output schema (your metadata fields)
        __init__.py   # thin wiring: schema + prompt + a source adapter -> PROJECT

The schema and prompt are the two things you actually edit; __init__.py is a
small declaration. Answers from a short questionnaire pick the source adapter.
"""

from __future__ import annotations

import re
from pathlib import Path

PROMPT_STUB = """\
You are extracting catalogue metadata from a digitised item for a library or
archive. Look at the image(s) and return a single JSON object matching the
schema. Emit JSON only — no commentary or markdown.

TODO: describe each field of the schema and how to handle edge cases. The
quality of extraction depends almost entirely on this prompt.
"""

SCHEMA_HEADER = '''\
"""Output schema for {name}. Edit these fields (keep prompt.md in step)."""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Record(BaseModel):
    # TODO: set types and describe each field for the prompt.
'''

def to_module_name(name: str) -> str:
    return re.sub(r"[^0-9a-zA-Z]+", "_", name.strip().lower()).strip("_")


def _render_schema(name: str, fields: list[str]) -> str:
    names = [to_module_name(f) for f in fields if to_module_name(f)] or ["title"]
    lines = [
        f'    {f}: Optional[str] = Field(None, description="TODO: describe {f}")'
        for f in names
    ]
    return SCHEMA_HEADER.format(name=name) + "\n".join(lines) + "\n"


def _source_expr(kind: str, verso: bool, crop: bool) -> tuple[str, str]:
    """Return (import_name, call_expr) for the chosen source adapter."""
    if kind == "pdf":
        return "pdf_source", "pdf_source()"
    return "image_source", f"image_source(verso_filter={verso}, crop={crop})"


def render_project(
    name: str,
    *,
    kind: str = "images",
    verso: bool = False,
    crop: bool = False,
    fields: list[str] | None = None,
):
    """Return ``{filename: content}`` for a new project. ``kind`` is
    ``"images"`` or ``"pdf"``; ``verso``/``crop`` apply to image projects;
    ``fields`` seeds the schema (defaults to a single ``title``)."""
    mod = to_module_name(name)
    ep_name = mod.replace("_", "-")
    src_import, src_call = _source_expr(kind, verso, crop)

    init_py = f'''\
"""{name} project — generated by `paratext new`. Edit schema.py and prompt.md."""

from __future__ import annotations

from paratext.projects import Project, load_prompt
from paratext.sources import {src_import}

from .schema import Record

PROJECT = Project(
    name="{ep_name}",
    schema_version="v1",
    prompt=load_prompt(__file__),
    schema=Record,
    source={src_call},
)
'''
    return {
        f"{mod}/schema.py": _render_schema(name, fields or ["title"]),
        f"{mod}/prompt.md": PROMPT_STUB,
        f"{mod}/__init__.py": init_py,
    }


def _ask(question: str, default: bool) -> bool:
    suffix = " [Y/n] " if default else " [y/N] "
    ans = input(question + suffix).strip().lower()
    if not ans:
        return default
    return ans in ("y", "yes")


def init(name: str | None = None) -> int:
    """Interactive scaffold. Asks input type + (for images) verso/crop, writes
    the project files under ./<module>/, offers to add a paratext.toml config
    entry, and prints the register + run steps."""
    name = name or input("Project name: ").strip()
    if not name:
        raise SystemExit("a project name is required")

    is_pdf = _ask("Is the source PDFs (rather than images)?", default=False)
    kind = "pdf" if is_pdf else "images"
    verso = crop = False
    if kind == "images":
        verso = _ask("Filter blank versos (backs of cards) before the VLM?", default=True)
        crop = _ask("Crop each scan to the card region (RetinaNet from HF)?", default=False)

    raw = input("Metadata fields, comma-separated (e.g. title, author, date) [title]: ")
    fields = [f.strip() for f in raw.split(",") if f.strip()] or ["title"]

    files = render_project(name, kind=kind, verso=verso, crop=crop, fields=fields)
    mod = to_module_name(name)
    dest = Path.cwd() / mod
    if dest.exists():
        raise SystemExit(f"refusing to overwrite existing directory: {dest}")
    for rel, content in files.items():
        path = Path.cwd() / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    ep_name = mod.replace("_", "-")
    print(f"\nCreated ./{mod}/ (schema.py + prompt.md + __init__.py).")

    _offer_config(ep_name)
    registered = _offer_register(mod, ep_name)

    print("\nNext steps:")
    n = 1
    if not registered:
        print(f"  {n}. Register the project — add to your pyproject.toml:")
        print('       [project.entry-points."paratext.projects"]')
        print(f'       {ep_name} = "{mod}:PROJECT"')
        print("     then reinstall:  uv sync   (or: pip install -e .)")
        n += 1
    print(f"  {n}. Edit {mod}/prompt.md and {mod}/schema.py (keep them in step).")
    print(f"  {n + 1}. Run it:  paratext run -p {ep_name}")
    return 0


def _insert_entry_point(pyproject: Path, text: str, ep_name: str, mod: str) -> bool:
    """Add `ep_name = "<mod>:PROJECT"` under the paratext.projects entry-point
    table, creating the table if absent. Returns False if it can't do so safely."""
    line = f'{ep_name} = "{mod}:PROJECT"'
    header_re = re.compile(
        r'^\[project\.entry-points\.["\']paratext\.projects["\']\]\s*$', re.M
    )
    m = header_re.search(text)
    if m:
        pyproject.write_text(text[: m.end()] + "\n" + line + text[m.end():])
        return True
    if "paratext.projects" in text:
        return False  # a table exists but in a form we won't risk editing
    sep = "" if text.endswith("\n") else "\n"
    pyproject.write_text(text + f'{sep}\n[project.entry-points."paratext.projects"]\n{line}\n')
    return True


def _offer_register(mod: str, ep_name: str) -> bool:
    """If a pyproject.toml is present, offer to register the entry point and run
    `uv sync`. Returns True once the project is registered."""
    import tomllib

    pyproject = Path.cwd() / "pyproject.toml"
    if not pyproject.exists():
        return False  # no package to install into; fall back to printed steps
    text = pyproject.read_text()
    try:
        parsed = tomllib.loads(text)
    except tomllib.TOMLDecodeError:
        return False
    eps = (parsed.get("project", {}).get("entry-points", {}) or {}).get("paratext.projects", {})

    if ep_name in (eps or {}):
        print(f"  '{ep_name}' is already registered in pyproject.toml.")
    else:
        if not _ask(f"Register '{ep_name}' in pyproject.toml now?", default=True):
            return False
        if not _insert_entry_point(pyproject, text, ep_name, mod):
            print("  Couldn't safely edit pyproject.toml — add the entry point by hand.")
            return False
        print(f"  Registered '{ep_name}' in {pyproject.name}.")

    if _ask("Reinstall now so paratext can discover it (uv sync)?", default=True):
        import shutil
        import subprocess

        if shutil.which("uv"):
            subprocess.call(["uv", "sync"])
            # Confirm it's actually importable/discovered (catches src-layout
            # packages where a module in the repo root isn't installed).
            check = subprocess.run(
                ["uv", "run", "python", "-c",
                 f"from paratext.projects import project_names as p; "
                 f"import sys; sys.exit(0 if '{ep_name}' in p() else 1)"],
            )
            if check.returncode == 0:
                print(f"  Verified: '{ep_name}' is discovered by paratext.")
            else:
                print(f"  Note: '{ep_name}' isn't discovered yet — make sure {mod}/ is "
                      "part of your installed package (e.g. under the package root).")
        else:
            print("  uv not found — run `pip install -e .` to reinstall.")
    return True


def _offer_config(ep_name: str) -> None:
    """Optionally write a `[project.<name>]` block (and a top-level endpoint if the
    config has none) to paratext.toml, so the project is runnable without a
    separate `paratext config` trip."""
    import tomllib

    from .config import local_config_path

    if not _ask(f"Add a paratext.toml config entry for '{ep_name}' now?", default=True):
        return

    path = local_config_path()
    existing = path.read_text() if path.exists() else ""
    parsed = tomllib.loads(existing) if existing.strip() else {}
    if ep_name in (parsed.get("project") or {}):
        print(f"  paratext.toml already has [project.{ep_name}] — leaving it as is.")
        return

    source = input("  Source directory (images or PDFs) []: ").strip()

    block: list[str] = []
    if not existing.strip():
        block.append("# paratext config")
    if not any(k in parsed for k in ("base-url", "base_url")):
        base = input("  VLM base URL [http://localhost:8000/v1]: ").strip() \
            or "http://localhost:8000/v1"
        model = input("  Model id served by that endpoint []: ").strip()
        block.append(f'base-url = "{base}"')
        if model:
            block.append(f'model = "{model}"')
        block.append("")
    block.append(f"[project.{ep_name}]")
    block.append(f'source = "{source}"' if source else '# source = "path/to/your/data"')

    sep = "\n" if existing.strip() else ""
    with path.open("a") as f:
        f.write(sep + "\n".join(block) + "\n")
    print(f"  Wrote [project.{ep_name}] to {path}.")
