"""`paratext new` — scaffold a new project package.

Generates a project directory in the current working directory:

    <name>/
        prompt.md     # the prompt (prose, for the model)
        schema.py     # the Pydantic output schema (your metadata fields)
        __init__.py   # thin wiring: schema + prompt + a source adapter -> PROJECT

The schema and prompt are the two things you actually edit; __init__.py is a
small declaration. Answers from a short questionnaire pick the source adapter.
"""

from __future__ import annotations

import re
from pathlib import Path

PROMPT_STUB = """\
You are extracting catalogue metadata from a digitised item for a library or
archive. Look at the image(s) and return a single JSON object matching the
schema. Emit JSON only — no commentary or markdown.

TODO: describe each field of the schema and how to handle edge cases. The
quality of extraction depends almost entirely on this prompt.
"""

SCHEMA_HEADER = '''\
"""Output schema for {name}. Edit these fields (keep prompt.md in step)."""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Record(BaseModel):
    # TODO: set types and describe each field for the prompt.
'''

def to_module_name(name: str) -> str:
    return re.sub(r"[^0-9a-zA-Z]+", "_", name.strip().lower()).strip("_")


def _render_schema(name: str, fields: list[str]) -> str:
    names = [to_module_name(f) for f in fields if to_module_name(f)] or ["title"]
    lines = [
        f'    {f}: Optional[str] = Field(None, description="TODO: describe {f}")'
        for f in names
    ]
    return SCHEMA_HEADER.format(name=name) + "\n".join(lines) + "\n"


def _source_expr(kind: str, verso: bool, crop: bool) -> tuple[str, str]:
    """Return (import_name, call_expr) for the chosen source adapter."""
    if kind == "pdf":
        return "pdf_source", "pdf_source()"
    return "image_source", f"image_source(verso_filter={verso}, crop={crop})"


def render_project(
    name: str,
    *,
    kind: str = "images",
    verso: bool = False,
    crop: bool = False,
    fields: list[str] | None = None,
):
    """Return ``{filename: content}`` for a new project. ``kind`` is
    ``"images"`` or ``"pdf"``; ``verso``/``crop`` apply to image projects;
    ``fields`` seeds the schema (defaults to a single ``title``)."""
    mod = to_module_name(name)
    ep_name = mod.replace("_", "-")
    src_import, src_call = _source_expr(kind, verso, crop)
    extra = "" if kind == "images" else "# `pip install paratext[pdf]` for PDF rendering.\n"

    init_py = f'''\
"""{name} project — generated by `paratext new`. Edit schema.py and prompt.md."""

from __future__ import annotations

from paratext.projects import Project, load_prompt
from paratext.sources import {src_import}

from .schema import Record

{extra}PROJECT = Project(
    name="{ep_name}",
    schema_version="v1",
    prompt=load_prompt(__file__),
    schema=Record,
    source={src_call},
)
'''
    return {
        f"{mod}/schema.py": _render_schema(name, fields or ["title"]),
        f"{mod}/prompt.md": PROMPT_STUB,
        f"{mod}/__init__.py": init_py,
    }


def _ask(question: str, default: bool) -> bool:
    suffix = " [Y/n] " if default else " [y/N] "
    ans = input(question + suffix).strip().lower()
    if not ans:
        return default
    return ans in ("y", "yes")


def init(name: str | None = None) -> int:
    """Interactive scaffold. Asks input type + (for images) verso/crop, writes
    the project files under ./<module>/, and prints the entry-point line."""
    name = name or input("Project name: ").strip()
    if not name:
        raise SystemExit("a project name is required")

    is_pdf = _ask("Is the source PDFs (rather than images)?", default=False)
    kind = "pdf" if is_pdf else "images"
    verso = crop = False
    if kind == "images":
        verso = _ask("Filter blank versos (backs of cards) before the VLM?", default=True)
        crop = _ask("Crop each scan to the card region (RetinaNet from HF)?", default=False)

    raw = input("Metadata fields, comma-separated (e.g. title, author, date) [title]: ")
    fields = [f.strip() for f in raw.split(",") if f.strip()] or ["title"]

    files = render_project(name, kind=kind, verso=verso, crop=crop, fields=fields)
    mod = to_module_name(name)
    dest = Path.cwd() / mod
    if dest.exists():
        raise SystemExit(f"refusing to overwrite existing directory: {dest}")
    for rel, content in files.items():
        path = Path.cwd() / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    ep_name = mod.replace("_", "-")
    print(f"\nCreated ./{mod}/ (schema.py + prompt.md + __init__.py).")
    print("\nRegister it by adding this to your pyproject.toml, then reinstall:\n")
    print('  [project.entry-points."paratext.projects"]')
    print(f'  {ep_name} = "{mod}:PROJECT"\n')
    print(f"Then edit {mod}/schema.py and {mod}/prompt.md, and run "
          f"`paratext run -p {ep_name}`.")
    return 0
