"""`paratext init` — scaffold a new project package.

Generates a ready-to-edit project directory (``__init__.py`` + ``prompt.md``)
in the current working directory, wired to the answers from a short
questionnaire, and prints the entry-point line to register it. The generated
``__init__.py`` is a working starting point; the user then edits the schema and
prompt for their own metadata fields.
"""

from __future__ import annotations

import re
from pathlib import Path

PROMPT_STUB = """\
You are extracting catalogue metadata from a digitised item for a library or
archive. Look at the image(s) and return a single JSON object matching the
schema. Emit JSON only — no commentary or markdown.

TODO: describe each field of the schema and how to handle edge cases. The
quality of extraction depends almost entirely on this prompt.
"""

# Image-source iter_samples, optionally with the verso filter and/or crop.
_IMAGE_ITER = '''\
def _iter_samples(source: Path, limit: int | None) -> Iterator[Sample]:
    if not source.is_dir():
        raise FileNotFoundError(f"images dir not found: {{source}}")
    images = sorted(
        p for p in source.iterdir() if p.suffix.lower() in {{".jpg", ".jpeg", ".png"}}
    )
    if limit is not None:
        images = images[:limit]
{detector_setup}
    for img_path in images:
        img = Image.open(img_path).convert("RGB"){verso_block}{crop_block}
        yield Sample(
            id=img_path.stem,
            images=[img],
            metadata={{"image_path": str(img_path.resolve())}},
        )
'''

_VERSO_BLOCK = """
        if is_verso(img):
            yield Sample(
                id=img_path.stem,
                images=[],
                metadata={
                    "image_path": str(img_path.resolve()),
                    "preclassified": {"_skipped": "verso"},
                },
            )
            continue"""

_CROP_BLOCK = """
        bbox = detector.detect(img) if detector is not None else None
        if bbox is not None:
            img = detector.crop(img, bbox=bbox, padding_pct=0.10)"""

_PDF_ITER = '''\
def _iter_samples(source: Path, limit: int | None) -> Iterator[Sample]:
    if not source.is_dir():
        raise FileNotFoundError(f"PDF dir not found: {source}")
    pdfs = sorted(source.rglob("*.pdf"))
    if limit is not None:
        pdfs = pdfs[:limit]
    for pdf_path in pdfs:
        pdf = pdfium.PdfDocument(pdf_path)
        try:
            n = len(pdf)
            indices = list(range(min(3, n)))  # first 3 pages; edit as needed
            images = [pdf[i].render(scale=2.0).to_pil().convert("RGB") for i in indices]
        finally:
            pdf.close()
        yield Sample(
            id=pdf_path.stem,
            images=images,
            metadata={"pdf_path": str(pdf_path.resolve()), "pages_rendered": indices},
        )
'''


def to_module_name(name: str) -> str:
    return re.sub(r"[^0-9a-zA-Z]+", "_", name.strip().lower()).strip("_")


def render_project(name: str, *, kind: str = "images", verso: bool = False, crop: bool = False):
    """Return ``{filename: content}`` for a new project. ``kind`` is
    ``"images"`` or ``"pdf"``; ``verso``/``crop`` apply to image projects."""
    mod = to_module_name(name)

    if kind == "pdf":
        imports = (
            "import pypdfium2 as pdfium\n"
            "from pydantic import BaseModel, Field\n\n"
            "from paratext.projects import Panel, Project, Sample, View, load_prompt"
        )
        iter_src = _PDF_ITER
        extra = "    # `pip install paratext[pdf]` for pypdfium2.\n"
    else:
        card_imports = ""
        detector_setup = ""
        if crop:
            card_imports = "from paratext.cards import load_card_detector\n"
            detector_setup = "\n    detector = load_card_detector()  # None → no crop\n"
        if verso:
            card_imports = "from paratext.cards import is_verso" + (
                ", load_card_detector\n" if crop else "\n"
            )
        imports = (
            "from PIL import Image\n"
            "from pydantic import BaseModel, Field\n\n"
            + card_imports
            + "from paratext.projects import Panel, Project, Sample, View, load_prompt"
        )
        iter_src = _IMAGE_ITER.format(
            detector_setup=detector_setup,
            verso_block=_VERSO_BLOCK if verso else "",
            crop_block=_CROP_BLOCK if crop else "",
        )
        extra = ""

    init_py = f'''\
"""{name} project — generated by `paratext init`. Edit the schema and prompt."""

from __future__ import annotations

from pathlib import Path
from typing import Iterator, Optional

{imports}

SCHEMA_VERSION = "v1"


class Record(BaseModel):
    # TODO: replace with your metadata fields (keep names in sync with prompt.md).
    title: Optional[str] = Field(None, description="Example field")


PROMPT = load_prompt(__file__)  # see prompt.md beside this module


{extra}{iter_src}

VIEW = View(
    layout="split",
    title="{name}",
    id_label="ID",
    panels=[Panel(source="model_output", title="Model output", fields=["title"])],
)

PROJECT = Project(
    name="{mod.replace("_", "-")}",
    schema_version=SCHEMA_VERSION,
    prompt=PROMPT,
    schema=Record,
    iter_samples=_iter_samples,
    view=VIEW,
)
'''
    # Thin __init__.py re-exporting PROJECT; logic lives in project.py.
    return {
        f"{mod}/project.py": init_py,
        f"{mod}/__init__.py": 'from .project import PROJECT\n\n__all__ = ["PROJECT"]\n',
        f"{mod}/prompt.md": PROMPT_STUB,
    }


def _ask(question: str, default: bool) -> bool:
    suffix = " [Y/n] " if default else " [y/N] "
    ans = input(question + suffix).strip().lower()
    if not ans:
        return default
    return ans in ("y", "yes")


def init(name: str | None = None) -> int:
    """Interactive scaffold. Asks input type + (for images) verso/crop, writes
    the project files under ./<module>/, and prints the entry-point line."""
    name = name or input("Project name: ").strip()
    if not name:
        raise SystemExit("a project name is required")

    is_pdf = _ask("Is the source PDFs (rather than images)?", default=False)
    kind = "pdf" if is_pdf else "images"
    verso = crop = False
    if kind == "images":
        verso = _ask("Filter blank versos (backs of cards) before the VLM?", default=True)
        crop = _ask("Crop each scan to the card region (RetinaNet from HF)?", default=False)

    files = render_project(name, kind=kind, verso=verso, crop=crop)
    mod = to_module_name(name)
    dest = Path.cwd() / mod
    if dest.exists():
        raise SystemExit(f"refusing to overwrite existing directory: {dest}")
    for rel, content in files.items():
        path = Path.cwd() / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    ep_name = mod.replace("_", "-")
    print(f"\nCreated ./{mod}/ (__init__.py + prompt.md).")
    print("\nRegister it by adding this to your pyproject.toml, then reinstall:\n")
    print('  [project.entry-points."paratext.projects"]')
    print(f'  {ep_name} = "{mod}:PROJECT"\n')
    print(f"Then edit {mod}/prompt.md and the Record schema, and run "
          f"`paratext run -p {ep_name}`.")
    return 0
